### ISSUE TITLE
there should be a debug mode for python-wechaty

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/python-wechaty-puppet#11]
`python-wechaty` is at a early stage which need more detail running detail information for debugging.  We have occured some problems that we can't reproduction error from the issue and we can't find more detail information to fix. So, we should enable debug mode for `python-wechaty` by default which can output all of the `debug-level` info into log file, so the user can easily put log file to the issues to check the error. 

When `python-wechaty` is at a stable stage, we can change the debug mode to false by default. Should we do it ? @huan

**Comment by huan** [comment]
I think one of the solution would be following the TS style: set `WECHATY_LOG` to enable the log output, and use redirect to save log messages to file?

**Comment by wj-Mcat** [comment]
@huan I think we should save log message to file at this early stage. There are some reasons:
- debug information is too detaile d

**Comment by huan** [comment]
I think this solution is ok for me.

Please go ahead with it.
