### ISSUE TITLE
 issues at deploy stage

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/python-wechaty-puppet#3]
I check the action log, which shows `semver` has been installed. 

![image](https://user-images.githubusercontent.com/10242208/82546399-9ec93500-9b8a-11ea-8d99-2fdac35a4436.png)

This error occured at final stage.

I wanna to depoly `wechaty`, `wechaty-puppet` and `wechat-puppet-hostie` packages today.

**Comment by huan** [comment]
I'm trying to fix this issue, and it seems work.

Please check and let me know if there's any other problems with it.

P.S. I have disabled the `pytype` because it seems that the Python 3.7+ is not supported by it.

**Comment by huan** [comment]
CI/CD seems to work.

A new PyPI version has been published.

**Comment by wj-Mcat** [comment]
Great to hear that
