### ISSUE TITLE
EventHeartbeatPayload payload data structure error.

### ISSUE THREAD

**Issue by zavierxu** [wechaty/python-wechaty-puppet#6]
When wechaty puppet recieved a heartbeat from hostie, an error occured: `TypeError: __init__() got an unexpected keyword argument 'timeout'`

https://github.com/wechaty/python-wechaty-puppet/blob/984e17390a78a406dc224b8538ee3d48b4ce9405/src/wechaty_puppet/schemas/event.py#L132-L134
Here class `EventHeartbeatPayload()` only defined one of the arguments `data`, left `timeout` behind, which may cause this error.

**Comment by wj-Mcat** [comment]
@zavierxu it's a greate issue about `heartbeat` event payload.  This is translated from [wechaty-puppet](https://github.com/wechaty/wechaty-puppet). This is a really data structure bug for python-wechaty-puppet, Thank your for finding it.

https://github.com/wechaty/wechaty-puppet/blob/ac9c87017234432d716fe55aa88874d22dd03412/src/schemas/event.ts#L80-L82

@huan  I wonder if this is also a bug for wechaty-puppet ?

**Comment by huan** [comment]
What kind of bug so you think it is, could you please describe it in details?

**Comment by wj-Mcat** [comment]
`python-wechaty-puppet-hostie` receive `EventHeartBeatPayload` from `hostie-server` with two fields: `data`, `timeout`.  I translate from `puppet-wechaty`, so `EventHeartBeatPayload` in `python-wechaty` have only one field: `data`.  [wechaty-puppet](https://github.com/wechaty/wechaty-puppet/blob/master/src/schemas/event.ts#L80) also have one field: `data`

I wonder if this is also a bug for wechaty-puppet ?

**Comment by zavierxu** [comment]
According to TypeScript handbook : https://www.typescriptlang.org/docs/handbook/interfaces.html#our-first-interface

> Notice we didn’t have to explicitly say that the object we pass to printLabel implements this interface like we might have to in other languages. Here, it’s only the shape that matters. If the object we pass to the function meets the requirements listed, then it’s allowed.

So, it's valid in TypeScript, but not in Python

**Comment by wj-Mcat** [comment]
@zavierxu Thank you for reminding me. I have fixed this issue. Please reinstall `wechaty-puppet` pypi package later after this pr #7 being merged.

**Comment by wj-Mcat** [comment]
@huan although this is valid in grammar, but `timeout` field is actually leave out.

**Comment by zavierxu** [comment]
> @zavierxu Thank you for reminding me. I have fixed this issue. Please reinstall `wechaty-puppet` pypi package later after this pr #7 being merged.

Thanks dude

**Comment by huan** [comment]
Thanks for the explanation and the fix.

It seems that the `timeout` property is unexpected data received from the server.

I believe we should always align with our golden truth from: `wechaty-puppet`. So the https://github.com/wechaty/wechaty-puppet/blob/ac9c87017234432d716fe55aa88874d22dd03412/src/schemas/event.ts#L80-L82, which you have used before should be the right data structure:

```ts
export interface EventHeartbeatPayload {
  data: string,
}
```

However, when we receive a payload that contains unexpected property, it seems that the Python dataclass will raise an exception?

Could we make the Python dataclass just ignore the unexpected property? If we can, I believe we can do that.

Or if it can't, then I agree with you that the #7 will be a good workaround.

At last, if we can find the reason that the puppet server sends the `timeout`, we can fix this problem at the server-side. a PR will be welcome if anyone can figure it out.

**Comment by wj-Mcat** [comment]
Ok,I will try to fix unexpected field exception at dataclass.

**Comment by zavierxu** [comment]
There are several workgrounds,for example [this one](https://stackoverflow.com/questions/54678337/how-does-one-ignore-extra-arguments-passed-to-a-data-class), but it seems there is not an official way to do this.

**Comment by huan** [comment]
I have proposed a PR at https://github.com/wechaty/python-wechaty-puppet-hostie/pull/7, it's very concise and clean, I think it should be able to solve this problem?

**Comment by zavierxu** [comment]
It seems that this issue has been solved. I will close this issue.

**Comment by huan** [comment]
@wechaty/java @wechaty/go There are developers in our WeChat group talking about this issue, and so I mention you guys and hope we can fix it in languages other than Python as well.

See:

![image](https://user-images.githubusercontent.com/1361891/83236322-eae92a80-a1c5-11ea-83cc-b57cbf9af9c7.png)
